%% Graphical user interface for the LaserStarInc software
% Common objects for the whole interface
% dummy patient name
%#########################
handles.physicianName = 'Dr. Acula';

cornerTextPhysician = sprintf('Physician: %s', handles.physicianName);

% if patientLogged
%    
% end
%#########################
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
handles.fig = figure(...
    'Visible', 'on',...
    'Position', [0 0 1280 720],...
    'Name', 'LaserStarInc', ...
    'Tag', 'fig',...
    'Toolbar', 'none', ...
    'MenuBar', 'none');

handles.background = uipanel(...
    'Title','',...
    'Position',[190/1280 40/720 1020/1280 640/720],...
    'BackgroundColor', 'white',...
    'Visible', 'on');

handles.commonPhysicianLabel = uicontrol(...
    'Parent', handles.background,...
    'Style', 'Text',...
    'BackgroundColor', 'white',...
    'Units', 'normalized',...
    'FontUnits', 'normalized',...
    'Position', [5/1020 610/640 350/1020 24/640],...
    'HorizontalAlignment', 'left',...
    'FontSize', 0.7,...
    'FontUnits', 'normalized');

handles.commonPatientIDLabel = uicontrol(...
    'Parent', handles.background,...
    'Style', 'Text',...
    'BackgroundColor', 'white',...
    'Units', 'normalized',...
    'FontUnits', 'normalized',...
    'Position', [425/1020 610/640 500/1020 24/640],...
    'HorizontalAlignment', 'right',...
    'FontUnits', 'normalized',...
    'FontSize', 0.7);

% Start Page
%--------------------------------------------------------------------------
handles.startPagePanel = uipanel(...
    'Parent', handles.background,...
    'Units', 'normalized',...
    'Position', [0 0 1 1],...
    'BackgroundColor', 'white',...
    'Visible', 'on');

% label enter Physician Name here 1020 720
handles.physicianNameLabel = uicontrol(...
    'Parent', handles.startPagePanel,...
    'Units', 'normalize',...
    'Position', [0.27 0.55 0.6 0.1],...
    'Style', 'Text',...
    'FontUnits', 'normalized',...
    'FontSize', 0.6,...
    'String', 'Enter Physician Name',...
    'HorizontalAlignment', 'left',...
    'BackgroundColor', 'white');

handles.physicianNameEdit = uicontrol(...
    'Parent', handles.startPagePanel,...
    'Units', 'normalized',...
    'Style', 'Edit',...
    'Position', [0.27 0.49 0.5 0.065]);
    
handles.physicianNameEnter = uicontrol(...
    'Parent', handles.startPagePanel,...
    'Units', 'normalized',...
    'Style', 'Pushbutton',...
    'Position', [0.27 0.4 0.3 0.07],...
    'FontUnits', 'normalized',...
    'FontSize', 0.6,...
    'String', 'Enter',...
    'Callback', @physicianNameEnter_Callback);

% editfiel to enter physician name 

% enter button



%--------------------------------------------------------------------------
% videoPanel
handles.videoPanel = uipanel(...
    'Parent', handles.background,...
    'Position', [445/1020 35/640 540/1020 570/640],...
    'Bordertype','none',...
    'Visible', 'off');

        handles.videoStream = axes(...
            'Parent', handles.videoPanel, ...
            'Color', 'white',...
            'Position', [0 0 1 1]);
        
%--------------------------------------------------------------------------

%predifined dummy variables
%#################################################
minIso = 0; maxIso = 12; iso = 0; % the number represents e.g. 50*(2^minIso)
minExposure = 3; maxExposure = 12; exposure = 12;
minKernel = 3; maxKernel = 5; kernel = 3;

minKernelLabel = [num2str(minKernel*2-1) 'x' num2str(minKernel*2-1)];
maxKernelLabel = [num2str(maxKernel*2-1) 'x' num2str(maxKernel*2-1)];
%currentKernelLabel = [num2str(handles.kernSlider.Value) 'x' num2str(handles.kernSlider.Value)]; 
%#################################################

% Settings Window panel [reorganized by dedicated panel]
% panel half the size of the background panel
handles.settingsPanel = uipanel(...
    'Parent', handles.background, ...
    'Position', [0 0 425/1020 605/640],...
    'Bordertype', 'none',...
    'Visible', 'off', ...
    'BackgroundColor', 'white');

        % kernel size axis for the image [checkup needed for images]
        handles.kernelImg = axes(...
            'Parent', handles.settingsPanel,...
            'Position', [49/425 360/605 64/425 64/605]);
        
        % lable for kernel
        handles.kernelLabel = uicontrol(...
            'Parent', handles.settingsPanel,...
            'Units', 'Normalized',...
            'Position', [49/425 330/605 70/425 30/605],...
            'FontUnits', 'normalized',...
            'Style', 'Text',...
            'String', 'Kernel',...
            'FontSize', 0.7,...
            'HorizontalAlignment', 'left',...
            'BackgroundColor', 'White');
        
        % label for minimum kernel size
        handles.kernelMinLabel = uicontrol(...
            'Parent', handles.settingsPanel,...
            'Units', 'Normalized',...
            'FontUnits', 'normalized',...
            'Position', [145/425 330/605 60/425 30/605],...
            'Style', 'Text',...
            'String', minKernelLabel,...
            'FontSize', 0.7,...
            'HorizontalAlignment', 'left',...
            'BackgroundColor', 'White');
        
        % label for maximum kernel size
         handles.kernelMaxLabel = uicontrol(...
            'Parent', handles.settingsPanel,...
            'Units', 'Normalized',...
            'FontUnits', 'normalized',...
            'Position', [325/425 330/605 60/425 30/605],...
            'Style', 'Text',...
            'String', maxKernelLabel,...
            'FontSize', 0.7,...            
            'HorizontalAlignment', 'right',...
            'BackgroundColor', 'White');
        
        % slider to set the kernel size
        handles.kernelSizeSlider = uicontrol(...
            'Parent', handles.settingsPanel, ...
            'Tag', 'kernelSize',...
            'Min',minKernel,'Max',maxKernel,'Value',kernel,...
            'SliderStep', [1/3 1],...
            'Units','normalized',...
            'Style', 'Slider',...
            'Position', [145/425 392/605 240/425 10/605],...            
            'Callback', @kernelSizeSlider_Callback);
            
        
        
        %#########################################################
        currentKernelLabel = [num2str(handles.kernelSizeSlider.Value*2-1)...
            'x' num2str(handles.kernelSizeSlider.Value*2-1)]; 

        % label showing the current kernel size
         handles.kernelCurrentLabel = uicontrol(...
            'Parent', handles.settingsPanel,...
            'Units', 'Normalized',...
            'Position', [235/425 330/605 60/425 30/605],...
            'FontUnits', 'normalized',...
            'Style', 'Text',...
            'String', currentKernelLabel,...
            'FontSize', 0.7,...
            'BackgroundColor', 'White');
        
        %#########################################################
        % Gain size axis for the image [checkup needed for images]
%         handles.gainImg = axes(...
%             'Parent', handles.settingsPanel,...
%             'Position', [49/425 360/605 64/425 64/605]);
        
%         % lable for gain
%         handles.gainLabel = uicontrol(...
%             'Parent', handles.settingsPanel,...
%             'Units', 'Normalized',...
%             'Position', [58/425 330/605 80/425 30/605],...
%             'FontUnits', 'normalized',...            
%             'Style', 'Text',...
%             'String', 'Gain',...
%             'FontSize', 0.7,...
%             'HorizontalAlignment', 'left',...
%             'BackgroundColor', 'White');
%         
%         % label for minimum gain
%         handles.minGainLabel = uicontrol(...
%             'Parent', handles.settingsPanel,...
%             'Units', 'Normalized',...
%             'Position', [145/425 330/605 60/425 30/605],...
%             'FontUnits', 'normalized',...
%             'Style', 'Text',...
%             'String', minIso,...
%             'FontSize', 0.7,...
%             'HorizontalAlignment', 'left',...
%             'BackgroundColor', 'White');
%         
%         % label for maximum exposure
%          handles.maxGainLabel = uicontrol(...
%             'Parent', handles.settingsPanel,...
%             'Units', 'Normalized',...
%             'Position', [325/425 330/605 60/425 30/605],...
%             'FontUnits', 'normalized',...            
%             'Style', 'Text',...
%             'String', maxIso,...
%             'FontSize', 0.7,...
%             'HorizontalAlignment', 'right',...
%             'BackgroundColor', 'White');

%         % slider to set the gain
%         handles.gainSlider = uicontrol(...
%             'Parent', handles.settingsPanel,...
%             'Min',minIso,'Max',maxIso,'Value',iso,...
%             'Units','normalized',...
%             'Style', 'slider', ...
%             'SliderStep', [1/12 2],...
%             'Position', [145/425 392/605 240/425 10/605],...
%             'Callback', @gainSlider_Callback);
        %#################################################
        % current gain value
% %         currentgainLabel = handles.gainSlider.Value;
% 
%         % label showing the current kernel size
%          handles.gainCurrentLabel = uicontrol(...
%             'Parent', handles.settingsPanel,...
%             'Units', 'Normalized',...
%             'Position', [235/425 330/605 60/425 30/605],...
%             'FontUnits', 'normalized',...
%             'Style', 'Text',...
%             'String', currentgainLabel,...
%             'FontSize', 0.7,...            
%             'BackgroundColor', 'White');
        %################################################
        
        % Exposure size axes for the image [checkup needed for images]
        handles.exposureImg = axes(...
            'Parent', handles.settingsPanel, ...
            'Position', [49/425 504/605 64/425 64/605]);
        
        % lable for exposure
        handles.exposureLabel = uicontrol(...
            'Parent', handles.settingsPanel,...
            'Units', 'Normalized',...
            'Position', [37/425 474/605 120/425 30/605],...
            'FontUnits', 'normalized',...
            'Style', 'Text',...
            'String', 'Exposure',...
            'FontSize', 0.7,...       
            'HorizontalAlignment', 'left',...
            'BackgroundColor', 'White');
        
        % label for minimum exposure
        handles.exposureMinLabel = uicontrol(...
            'Parent', handles.settingsPanel,...
            'Units', 'Normalized',...
            'Position', [145/425 474/605 60/425 30/605],...
            'FontUnits', 'normalized',...
            'Style', 'Text',...
            'String', minExposure,...
            'FontSize', 0.7,...
            'HorizontalAlignment', 'left',...
            'BackgroundColor', 'White');
        
        % label for maximum exposure
         handles.exposureMaxLabel = uicontrol(...
            'Parent', handles.settingsPanel,...
            'Units', 'Normalized',...
            'Position', [325/425 474/605 60/425 30/605],...
            'FontUnits', 'normalized',...
            'Style', 'Text',...
            'String', maxExposure,...
            'FontSize', 0.7,...
            'HorizontalAlignment', 'right',...
            'BackgroundColor', 'White');
        

        % slider to set the exposure
        handles.exposureSlider = uicontrol(...
            'Parent', handles.settingsPanel,...
            'Min',minExposure,'Max',maxExposure,'Value',exposure,...
            'Units','normalized',...
            'Style', 'slider', ...
            'SliderStep', [1/3 1],...
            'Position', [145/425 536/605 240/425 10/605],...
            'Callback',@exposureSlider_Callback);
        %###################################################
        % current gain value
        currentExposureLabel = handles.exposureSlider.Value;

        % label showing the current kernel size
         handles.exposureCurrentLabel = uicontrol(...
            'Parent', handles.settingsPanel,...
            'Units', 'Normalized',...
            'Position', [235/425 474/605 60/425 30/605],...
            'FontUnits', 'normalized',...
            'Style', 'Text',...
            'String', currentExposureLabel,...
            'FontSize', 0.7,...            
            'BackgroundColor', 'White');

% MEASURE
%##########################################################################
%##########################################################################

% Measure panel with common elements
%--------------------------------------------------------------------------

handles.measurePanel = uipanel(...
    'Parent', handles.background, ...
    'Position', [0 0 425/1020 605/640],...
    'Bordertype', 'none',...
    'Visible', 'off', ...
    'BackgroundColor', 'white');

% % PATIENT
%##########################################################################
%##########################################################################

% measure: Patient windows section
%--------------------------------------------------------------------------

%panel for the patient button
handles.patientPanel = uipanel(...
    'Parent', handles.measurePanel,...
    'Position', [0 0  1 460/605],...
    'Bordertype', 'none', ...
    'BackgroundColor', 'white', ...
    'Visible', 'off');

        % Label indicating the user to enter the patientID
        handles.patientIDLabel = uicontrol(...
            'Parent', handles.patientPanel,...
            'Style', 'Text',...
            'Units','normalized',...
            'String', 'Enter PatientID',...
            'FontUnits', 'normalized',...
            'FontSize', 0.7,...
            'Position', [35/425 417/460 380/425 48/460],...
            'HorizontalAlignment','left', ...
            'BackgroundColor', 'white');

        handles.patientIDField = uicontrol(...
            'Parent', handles.patientPanel,...
            'Units','normalized',...
            'Style', 'Edit', ...
            'Position', [35/425 377/460 380/425 30/460]);

        handles.enterButton = uicontrol(...
            'Parent', handles.patientPanel, ...
            'Style', 'pushbutton', ...
            'Units','normalized',...
            'FontUnits', 'normalized',...
            'FontSize', 0.7,...
            'Position', [35/425 338/460 190/425 30/460],...
            'String', 'Enter',...
            'Callback', @enterButton_Callback);

        % Title to register new patient
        handles.registerPatientLabel = uicontrol(...
            'Parent', handles.patientPanel,...
            'Style', 'Text',...
            'Units','normalized', ...
            'Position', [35/425 268/460 380/425 48/460], ...
            'FontUnits', 'normalized',...
            'HorizontalAlignment', 'left',...
            'String', 'Register new Patient',...
            'FontSize', 0.7, ...
            'BackgroundColor', 'white');

        % Label indicating the user to enter name
        handles.nameLabel = uicontrol(...
            'Parent', handles.patientPanel,...
            'Style', 'Text', ...
            'String', 'Name', ...
            'Units','normalized', ...
            'FontUnits', 'normalized',...
            'FontSize', 0.7, ...
            'Position',[35/425 227/460 380/425 42/460], ...
            'HorizontalAlignment','left',...
            'BackgroundColor', 'white');

        % Name edit field
        handles.nameField = uicontrol(...
            'Parent', handles.patientPanel, ...
            'Style','Edit',...
            'Units','normalized',...
            'Position', [35/425 194/460 380/425 30/460]);

        % SSN Label
        handles.SSNLabel= uicontrol(...
            'Parent', handles.patientPanel, ...
            'Style', 'Text', ...
            'String','Social Security Number', ...
            'FontUnits', 'normalized',...
            'FontSize', 0.7,...
            'Units','normalized',... 
            'Position', [35/425 123/460 380/425 42/460],...
            'HorizontalAlignment','left',...
            'BackgroundColor', 'white');

        % SSN edit field
        handles.SSNEdit = uicontrol(...
            'Parent', handles.patientPanel,...
            'Units','normalized',...
            'Position', [35/425 89/460 380/425 30/460],...
            'Style','Edit');

        % Enter Button
        handles.enter2Button = uicontrol(...
            'Parent', handles.patientPanel,...
            'Units','normalized',...
            'FontUnits', 'normalized',...
            'Position', [35/425 50/460 190/425 30/460],...
            'Style', 'Pushbutton', ...
            'FontSize', 0.7,...
            'String', 'Save',...
            'Callback', @enter2Button_Callback);

% ROI
%##########################################################################
%##########################################################################

% Measure section: ROI
%--------------------------------------------------------------------------

% Panel for ROI1
handles.roi1Panel = uipanel(...
    'Parent', handles.measurePanel, ...
    'Position',[35/425 49/605 380/425 415/605], ...
    'BackgroundColor', 'white',...
    'Visible', 'off',...
    'Bordertype', 'none');

% % handles.roi2Panel = uipanel(...
% %     'Parent', handles.measurePanel,...
% %     'Position',[35/425 49/605 380/425 189/605], ...
% %     'BackgroundColor', 'white',...
% %     'Visible', 'off');

% Inside ROI1
%--------------------------------------------------------------------------

        % Size label
        handles.sizeLabel1 = uicontrol(...
            'Parent', handles.roi1Panel,...
            'Units','normalized', ...
            'Position', [0/380 550/605 1 48/460],...
            'FontUnits', 'normalized',...
            'FontSize', 0.7, ...            
            'String', 'Set ROI', ...
            'Style', 'Text', ...
            'HorizontalAlignment','left',...
            'BackgroundColor', 'white');


%##########################################################################
%##########################################################################



% Measure Window Start/Stop Recording
%--------------------------------------------------------------------------

% definition of the axes for the presentation of the average
% intensity of the perfusion 

% panel for the objects of measure window start stop recording
handles.startRecordingPanel = uipanel(...
    'Parent',handles.measurePanel, ...
    'Bordertype','none', ...
    'Position', [0 0 1 460/605], ...
    'Visible','off',...
    'BackgroundColor','white');


        handles.roiGraph = axes(...
            'Parent',handles.startRecordingPanel, ...
            'Position',[35/425 185/460 375/425 270/460])

%         % Add functionality here - display time recorded here
%         handles.timeRecordedLabel = uicontrol(...
%             'Parent', handles.startRecordingPanel, ...
%             'Units','normalized',...
%             'Position',[35/425 431/460 205/425 35/460], ...
%             'FontUnits', 'normalized',...
%             'Style', 'Text', ...
%             'String', 'Time Recorded:', ...
%             'HorizontalAlignment', 'left',...
%             'BackgroundColor', 'white',...
%             'FontSize', 0.7);
        
% datetime:
% timeRecorded = '00:12:13';
%         
%         hanldes.timeLabel = uicontrol(...
%             'Parent', handles.startRecordingPanel, ...
%             'Units','normalized',...
%             'Position',[240/425 431/460 185/425 35/460], ...
%             'FontUnits', 'normalized',...
%             'Style', 'Text', ...
%             'String', timeRecorded, ...
%             'HorizontalAlignment', 'right',...
%             'BackgroundColor', 'white',...
%             'FontSize', 0.7);

%##########################################################################
%##########################################################################

% measure window start/stop save
%--------------------------------------------------------------------------

        % panel housing all elements of save 

        handles.savePanel = uipanel(...
            'Parent', handles.measurePanel,...
            'Position',[0 0 1 460/605], ...
            'Visible', 'off',...
            'Bordertype', 'none',...
            'BackgroundColor', 'white');

                % smaller roiGraph
                handles.smallerRoiGraph = axes(...
                    'Parent',handles.savePanel,...
                    'Position',[35/425 35/460 380/425 288/460]);
                


                % panel conainting options on how to save
                handles.saveMeasurementPanel = uipanel(...
                    'Parent', handles.savePanel, ...
                    'Position',[35/425 336/460 380/425 110/460],  ...
                    'Visible', 'off', ...
                    'BackgroundColor', 'white');

                        % label examination name
                        handles.examinationNameLabel = uicontrol(...
                            'Parent', handles.saveMeasurementPanel,...
                            'Style', 'Text',...
                            'Units','normalized',...
                            'FontUnits', 'normalized',...
                            'String', 'Examination Name:', ...
                            'Position',[20/380 65/110 200/380 35/110], ...
                            'FontSize', 0.7,...
                            'HorizontalAlignment','left',...
                            'BackgroundColor', 'white');

                        % edit field examination name
                        handles.examinationNameEditField = uicontrol(...
                            'Parent', handles.saveMeasurementPanel,...
                            'Units','normalized',...
                            'Position', [20/380 25/110 250/380 30/110],...
                            'Style', 'Edit');

%##########################################################################
%##########################################################################

% HISTORY
%--------------------------------------------------------------------------
% history panel
handles.historyPanel = uipanel(...
    'Parent', handles.background, ...
    'Position',[0 0 1 605/640],...
    'Bordertype', 'none', ...
    'BackgroundColor', 'white',...
    'Visible','off');

        % panel housing the setup
        handles.enterPatientIDPanel = uipanel(...
            'Parent',handles.historyPanel, ...
            'Position',[530/1020 481/605 455/1020 110/605],...
            'BackgroundColor','white');

                % enter patient ID label
                handles.enterPatientLabel = uicontrol(...
                    'Parent', handles.enterPatientIDPanel,...
                    'Style', 'Text',...
                    'Units','normalized',...
                    'FontUnits', 'normalized',...
                    'Position', [20/455 51/110 250/455 48/110], ...
                    'String','Enter Patient ID',...
                    'FontSize', 0.7,...
                    'HorizontalAlignment','left', ...
                    'BackgroundColor', 'white');

                % enter patient ID edit field
                handles.enterPatientIDEditField = uicontrol(...
                    'Parent', handles.enterPatientIDPanel,...
                    'Style', 'Edit', ...
                    'Units','normalized',...
                    'Position', [20/455 25/110 260/455 27/110]);


% patient data table
%--------------------------------------------------------------------------
        % panel housing the data table
        handles.examinationTablePanel = uipanel(...
            'Parent', handles.historyPanel, ...
            'Position',[35/1020 35/605 950/1020 428/605], ...
            'BackgroundColor','white',...
            'Visible', 'off');

                % table storing the past examinations
                handles.examinationDataTable = uitable(...
                    'Parent', handles.examinationTablePanel,...
                    'Units','normalized',...
                    'Position',[0 0 1 1],...                    
                    'FontUnits', 'normalized',...
                    'FontSize', 0.04,...
                    ...'Data', [1,2,3,4,5,6,7,8,9,10,11,12],...
                    'ColumnName', {'Patient ID','Timestamp','Examination Name',...
                    'Physician','Gain','Exposure'...
                    'Kernel Size'},...
                    'CellSelectionCallback', @cellSelection_Callback);
                
% TODO: setting the length of the columns accordingly
% Database after logging the patient in

% register new patient
%--------------------------------------------------------------------------
        % panel housing the set new patient up objects
        handles.patientDBPanel = uipanel(...
            'Parent', handles.historyPanel, ...
            'Position',[35/1020 35/605 950/1020 428/605],...
            'Visible', 'off', ...
            'BackgroundColor','white');

                % setup new patient label
                handles.setupPatientLabel = uicontrol(...
                    'Parent', handles.patientDBPanel, ...
                    'Style','Text',...
                    'Units','normalized',...
                    'FontUnits', 'normalized',...
                    'FontSize', 0.8,...
                    'Position', [35/950 325/428 350/950 48/428],...
                    'String','Setup new Patient',...
                    'HorizontalAlignment','left', ...
                    'BackgroundColor', 'white');

                % name label
                handles.nameDBLabel = uicontrol(...
                    'Parent', handles.patientDBPanel, ...
                    'Style','Text',...
                    'FontUnits', 'normalized',...
                    'FontSize', 0.7, ...
                    'Units','normalized',...
                    'Position', [35/950 222/428 270/950 42/428],...
                    'String','Name:',...
                    'HorizontalAlignment','left',...
                    'BackgroundColor', 'white');

                % social security number label
                handles.SSNDBLabel = uicontrol(...
                    'Parent', handles.patientDBPanel, ...
                    'Style','Text',...
                    'FontUnits', 'normalized',...
                    'FontSize', 0.7, ...
                    'Units','normalized',...                    
                    'Position', [35/950 163/428 370/950 42/428], ...
                    'String','Social Security Number: ',...
                    'HorizontalAlignment','left',...
                    'BackgroundColor', 'white');

                handles.nameDBEdit = uicontrol(...
                    'Parent', handles.patientDBPanel, ...
                    'Style','Edit', ...
                    'Units','normalized',...
                    'Position', [150/950 230/428 665/950 30/428]);

                handles.SSNDBEdit = uicontrol(...
                    'Parent', handles.patientDBPanel,...
                    'Style','Edit',...
                    'Units','normalized',...
                    'Position', [425/950 170/428 390/950 30/428]);

% database after inserting patientID
%--------------------------------------------------------------------------
% panel containing all objects of the entry of an examination

% dummy values
%###########################
% examinationName = 'Examination: Upper left hand';
% exposureValue = sprintf('Exposure: %d ms',handles.exposureValue);
% gainValue = sprintf('Gain: ISO %d', handles.gainValue);
% kernelSizeValue = sprintf('Kernel size: %d x %d px', handles.kernelSize, handles.kernelSize);
% examinationDate = ['Examination date: ', date];
%###########################

handles.examinationPanel = uipanel(...
    'Parent', handles.background, ...
    'Position',[0 0 1 605/640],...
    'BackgroundColor','white',...
    'Bordertype','none',...
    'Visible', 'off');

        % panel housing the 3 displayed images
        handles.imageDisplayPanel = uipanel(...
            'Parent', handles.examinationPanel, ...
            'Position',[35/1020 35/605 950/1020 275/605], ...
            'BackgroundColor','white', ...
            'Visible', 'on');

                handles.image_T0 = axes(...
                    'Parent', handles.imageDisplayPanel, ...
                    'Position',[35/1020 80/640 220/1020 535/640 ]);

                handles.image_T1 = axes(...
                    'Parent', handles.imageDisplayPanel,...
                    'Position',[405/1020 80/640 220/1020 535/640 ]);

                handles.image_T2 = axes(...
                    'Parent', handles.imageDisplayPanel,...
                    'Position',[765/1020 80/640 220/1020 535/640 ]);

        % panel housing name and additional information
        handles.patientInfoPanel = uipanel(...
            'Parent', handles.examinationPanel,...
            'Position',[35/1020 330/605 355/1020 235/605],...
            'BackgroundColor','white',...
            'Visible', 'on');

                % Symbol of user
                handles.patientSymbolIcon = axes(...
                    'Parent', handles.patientInfoPanel, ...
                    'Position', [30/230 169/235 46/230 46/235]);

                handles.patientNameDBLabel = uicontrol(...
                    'Parent', handles.patientInfoPanel,...
                    'Units','normalized',...
                    'FontUnits', 'normalized',...
                    'Position', [86/230 193/235 129/230 28/235],...
                    'HorizontalAlignment', 'left',...
                    'Style', 'Text', ...
                    'FontSize', 0.7, ...
                    'BackgroundColor','white');

                % patient ID under the name right to the icon
                handles.patientIDDBLabel = uicontrol(...
                    'Parent', handles.patientInfoPanel,...
                    'Units','normalized',...
                    'FontUnits', 'normalized',...
                    'Position',[86/235 164/230 129/235 20/230],...
                    'HorizontalAlignment', 'left',...
                    'FontSize', 0.8, ...
                    'BackgroundColor','white',...
                    'Style','Text');

                % title of the examination
                handles.examinationTitleLabel = uicontrol(...
                    'Parent', handles.patientInfoPanel, ...
                    'Units','normalized',...
                    'Position',[20/235 120/230 200/235 28/230],...
                    'FontUnits', 'normalized',...
                    'FontSize', 0.7, ...
                    'Style','Text', ...
                    'HorizontalAlignment','left',...
                    'BackgroundColor', 'white');

                % label for exposure time
                handles.exposureValueLabel = uicontrol(...
                    'Parent', handles.patientInfoPanel,...
                    'Units','normalized',...
                    'Position',[20/235 10/230 200/235 22/230],...
                    'FontUnits', 'normalized',...
                    'FontSize', 0.7, ...
                    'BackgroundColor','white',...
                    'Style','Text', ...
                    'HorizontalAlignment','left');

                % label for exposure time
                handles.gainValueLabel = uicontrol(...
                    'Parent', handles.patientInfoPanel,...
                    'Units','normalized',...
                    'Position',[20/235 60/230 200/235 22/230],...
                    'FontUnits', 'normalized',...
                    'FontSize', 0.7, ...
                    'BackgroundColor','white', ...
                    'Style','Text', ...
                    'HorizontalAlignment','left');
                
                handles.examinationDateLabel = uicontrol(...
                    'Parent', handles.patientInfoPanel,...
                    'Units','normalized',...
                    'Position',[20/235 90/230 200/235 22/230],...
                    'FontUnits', 'normalized',...
                    'FontSize', 0.7, ...
                    'BackgroundColor','white', ...
                    'Style','Text', ...
                    'HorizontalAlignment','left');

                % label for kernel size
                handles.kernelSizeValueLabel = uicontrol(...
                    'Parent', handles.patientInfoPanel,...
                    'Units','normalized',...
                    'Position', [20/235 35/230 200/235 22/230],...
                    'FontUnits', 'normalized',...
                    'FontSize', 0.7, ...
                    'BackgroundColor','white',...
                    'Style','Text', ...
                    'HorizontalAlignment','left');

        % graph containing the measured roi values for the given
        % measurement
        handles.roiGraphDB = axes(...
            'Parent', handles.examinationPanel,...
            'Position', [415/1020 330/605 565/1020 275/605]);

handles.sectionButtonPanel = uipanel(...
    'Position', [49/1280 505/720 142/1280 142/720], ...
    'BackgroundColor', 'white');

handles.auxillaryPanel = uipanel(...
    'Position', [185/1280 507/720 10/1280 138/720],...
    'Bordertype', 'none', ...
    'BackgroundColor', 'white');


% loading in images
%#########################################################################

% load and scale history Icon image
historyIcon = imread('history copy.jpg');
historyIcon = imresize(historyIcon, 0.5);

% settings icon
settingsIcon = imread('settings-gears copy 2.jpg');

% measure icon
measureIcon = imread('measure copy.jpg');
measureIcon = imresize(measureIcon, 0.5);

stopIcon = imread('stop copy.jpg');
stopIcon = imresize(stopIcon, 0.5);

% user Icon
userIcon = imread('user.jpg');
imshow(userIcon, 'Parent', handles.patientSymbolIcon);

% contrast icon
exposureIcon = imread('contrast.jpg');
exposureIcon = imresize(exposureIcon, 0.0625);
imshow(exposureIcon, 'Parent', handles.exposureImg);

% kernel icon
kernelIcon = imread('kernelSize.jpg');
kernelIcon = imresize(kernelIcon, 0.5);
imshow(kernelIcon, 'Parent', handles.kernelImg);

% % gain icon
% gainIcon = imread('gain.jpg');
% gainIcon = imresize(gainIcon, 0.0625);
% imshow(gainIcon, 'Parent', handles.gainImg);

roiIcon = imread('ROI.jpg');

user64Icon = imread('User_64.jpg');

recordIcon = imread('record.jpg');

% BUTTONS
%#########################################################################
% laser stop button

% remove button to delete an existing ROI 1
handles.rmvROI1 = uicontrol(...
    'Parent', handles.roi1Panel,...
    'Units','normalized',...
    'FontUnits', 'normalized',...
    'FontSize', 0.5,...
    'Position', [0/380 223/605 145/380 100/605], ...
    'String', 'Rmv', ...
    'Style', 'Pushbutton',...
    'BackgroundColor','white',...
    'Callback', @rmvROI1_Callback);

% TODO: symbol for remove / add

% add button to create a new ROI1
handles.addROI1 = uicontrol(...
    'Parent', handles.roi1Panel,...
    'FontUnits', 'normalized',...
    'Units','normalized',...
    'Position', [0/380 430/605 145/380 100/605], ...
    'FontSize', 0.5,...
    'String', 'Add',...
    'Style', 'Pushbutton',...
    'BackgroundColor','white',...
    'Callback', @addROI1_Callback);

% % % remove button to delete an existing ROI 2
% % handles.rmvROI2 = uicontrol(...
% %     'Parent', handles.roi2Panel,...
% %     'Units','normalized',...
% %     'Position', [316/380 25/189 44/380 44/189], ...
% %     'String', 'Rmv',...
% %     'Style', 'Pushbutton');

% add button to create a new ROI2
% % handles.addROI2 = uicontrol(...
% %     'Parent', handles.roi2Panel,...
% %     'Units','normalized',...
% %     'Position', [316/380 99/189 44/380 44/189], ...
% %     'String', 'Add',...
% %     'Style', 'Pushbutton');

handles.laserStopButton = uicontrol(...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position', [65/1280 89/720 110/1280 110/720], ...
    ...'String', 'Stop Laser', ...
    'CData', stopIcon,...
    'BackgroundColor',[1 0 0],...    
    'Callback', @stopLaserButton_Callback);

% section button for history
handles.historyButton = uicontrol(...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position', [65/1280 233/720 110/1280 110/720],...
    ...'String', 'History',...
    'CData', historyIcon,...
    'BackgroundColor','white',...
    'Callback',@historyButton_Callback);

% section button for measure
handles.measureButton = uicontrol(...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position', [65/1280 377/720 110/1280 110/720],...
    ...'String', 'Measure',...
    'CData', measureIcon,...
    'BackgroundColor','white',...
    'Callback',@measureButton_Callback);

% section button for settings
handles.settingsButton = uicontrol(...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position', [65/1280 521/720 110/1280 110/720],...
    ...'String', 'Settings',...
    'CData', settingsIcon,...
    'BackgroundColor','white',...
    'Callback',{@settingsButton_Callback, handles});

% Button at the bottom responsible for starting the laser
handles.buttonStartSettings = uicontrol(...
    'Parent', handles.settingsPanel,...
    'Units', 'normalized', ...
    'Style', 'pushbutton',...
    'Position', [35/425 190/605 380/425 100/605],...
    'FontUnits', 'normalized',...
    'String','Try System with set Parameters',...
    'FontSize',0.24,...
    'BackgroundColor','white',...
    'Callback', {@startSystemWithSetParametersButton_Callback, handles});

handles.patientLogoutButton = uicontrol(...
    'Parent', handles.background,...
    'Style', 'pushbutton',...
    'BackgroundColor', 'white',...
    'Units', 'normalized',...
    'Position', [935/1020 610/640 80/1020 25/640],...
    'FontUnits', 'normalized',...
    ...'HorizontalAlignment', 'left',...
    'FontSize', 0.6,...
    'Visible', 'off',...
    'String', 'Logout',...
    'BackgroundColor','white',...
    'Callback',@patientLogoutButton_Callback);

% button for the ROI section
handles.roiButton = uicontrol(...
    'Parent', handles.measurePanel,...
    'Units','normalized',...
    'Style', 'pushbutton', ...
    'String', 'ROI',...
    'BackgroundColor','white',...
    'CData', roiIcon,...
    'Position',[170/425 481/605 110/425 110/605],...
    'Callback',{@roiButton_Callback,handles});

% patient Button
handles.patientButton = uicontrol(...
    'Parent', handles.measurePanel,...
    'Units','normalized',...
    'Style', 'pushbutton',...
    ...'String', 'Patient', ...
    'BackgroundColor','white',...
    'CData', user64Icon,...
    'Position',[35/425 481/605 110/425 110/605],...
    'Callback',{@patientButton_Callback,handles});

% start button for recording
handles.startRecordingButton = uicontrol(...
    'Parent', handles.measurePanel,...
    'Units','normalized',...
    'Style', 'pushbutton', ...
    ...'String', 'Start Recording',...
    'Position',[305/425 481/605 110/425 110/605], ...
    'Visible', 'on',...
    'CData', recordIcon,...
    'BackgroundColor','white',...
    'Callback',@startRecordingButton_Callback);

% stop button for recording
handles.stopRecordingButton = uicontrol(...
    'Parent', handles.measurePanel,...
    'Units','normalized',...
    'Style', 'pushbutton', ...
    ...'String', 'Stop Recording',...
    'Visible', 'off',...
    'BackgroundColor','white',...
    'Position',[305/425 481/605 110/425 110/605], ...
    'CData', stopIcon,...
    'Callback',@stopRecordingButton_Callback);


% save button for a finished examination
handles.saveExaminationButton = uicontrol(...
    'Parent', handles.saveMeasurementPanel,...
    'Style', 'Pushbutton',...
    'Units','normalized',...
    'Position', [290/380 25/110 70/380 30/110],...
    'FontUnits', 'normalized',...
    'FontSize', 0.6,...
    'String', 'Save', ...
    'BackgroundColor','white',...
    'Callback',@saveExaminationButton_Callback);

% new patient button
handles.newPatientButton = uicontrol(...
    'Parent', handles.historyPanel,...
    'Style', 'Pushbutton', ...
    'Units','normalized',...
    'Position', [35/1020 481/605 455/1020 110/605],...
    'FontUnits', 'normalized',...
    'String','Register New Patient',...
    'FontSize', 0.4,...
    'BackgroundColor','white',...
    'Callback', @newPatientButton_Callback);

% save button
handles.saveDBButton = uicontrol(...
    'Parent', handles.patientDBPanel, ...
    'Style','Pushbutton',...
    'FontUnits', 'normalized',...
    'Units','normalized',...
    'FontSize', 0.7,...    
    'Position', [35/950 90/428 270/950 50/428], ...
    'String','Save',...
    'BackgroundColor','white',...
    'Callback', @saveDBButton);

% patient ID button in history section
handles.enterpatientIDButton = uicontrol(...
    'Parent', handles.enterPatientIDPanel,...
    'Style', 'Pushbutton',...
    'Units','normalized',...
    'Tag', 'enterPatientIDButton',...
    'Position', [305/455 22/110 130/455 32/110], ...
    'FontUnits','normalized',...
    'String', 'Enter', ...
    'FontSize', 0.7,...
    'BackgroundColor','white',...
    'Callback',@enterPatientIDButton_Callback);

% return button on the examination panel 
handles.backToExaminationsButton = uicontrol(...
    'Parent', handles.examinationPanel,...
    'Units','normalized',...
    'Position', [35/1020 575/605 355/1020 30/605],...
    'FontUnits','normalized',...
    'String', 'Return', ...
    'FontSize',0.6, ...
    'Style', 'Pushbutton', ...
    'BackgroundColor','white',...
    'Callback', @returnButton_Callback);

%button initiating the recording of an image
handles.saveImage1 = uicontrol(...
    'Parent', handles.startRecordingPanel,...
    'Style', 'Pushbutton',...
    'Units', 'normalized',...
    'Position', [35/425 49/460 110/425 110/460],...
    'FontUnits', 'normalized',...
    'FontSize', 0.20,...
    'String', 'Image 1',...
    'BackgroundColor','white',...
    'Callback', @saveImage1_Callback)

guidata(handles.fig, handles);

handles.saveImage2 = uicontrol(...
    'Parent', handles.startRecordingPanel,...
    'Style', 'Pushbutton',...
    'Units', 'normalized',...
    'Position', [170/425 49/460 110/425 110/460],...
    'FontUnits', 'normalized',...
    'FontSize', 0.20,...
    'String', 'Image 2',...
    'BackgroundColor','white',...
    'Callback', @saveImage2_Callback)

guidata(handles.fig, handles);

handles.saveImage3 = uicontrol(...
    'Parent', handles.startRecordingPanel,...
    'Style', 'Pushbutton',...
    'Units', 'normalized',...
    'Position', [305/425 49/460 110/425 110/460],...
    'FontUnits', 'normalized',...
    'FontSize', 0.20,...
    'String', 'Image 3',...
    'BackgroundColor','white',...
    'Callback', @saveImage3_Callback)


%################################################################
% initializing column width of the table
pixelPosition = getpixelposition(handles.examinationDataTable);
width = pixelPosition(3);
handles.examinationDataTable.ColumnWidth =  {width*0.14, width*0.2, width*0.2, width*0.14, width*0.1, width*0.1, width*0.1};
%################################################################
handles.fig.SizeChangedFcn =  @SizeChangedFcn_Callback;

guidata(handles.fig, handles);

%####################################################







